spring.application.name=gachigayo
spring.profiles.active=local
spring.mail.host=smtp.naver.com
spring.mail.port=465
server.port=20000

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# \uB85C\uADF8
logging.level.com.baegopa.onestep=debug